### ISSUE TITLE
Attribute 'use' on xsl:context-item incorrectly marked as invalid

### ISSUE THREAD

**Issue by jperterm** [DeltaXML/vscode-xslt-tokenizer#105]
When using the `use` attribute with `xsl:context-item`, it is highlighted as an error even though it is valid XSL. It seems like the starting quote is treated as value for `use`.

```
<xsl:template name="test">
        <xsl:context-item as="element()" use="optional"/>
        <xsl:copy-of select="current()"/>
</xsl:template>
```

![grafik](https://user-images.githubusercontent.com/5832001/189087282-cc75e0a5-8b9b-4c64-be40-559ee4c38140.png)

**Comment by pgfearo** [comment]
Thanks for reporting this issue, I'll report back when I know more.

**Comment by pgfearo** [comment]
After initial investigation: 

The XSLT tokeniser is at fault here. It is tokenizing the `use` attribute value as XPath because the 'use' attribute *is* an XPath expression on many other XSLT elements. (The lexer is schema-aware and is not expecting an XPath token here.)

The tokenizer must treat `xsl:global-context-item` and `xsl:context-item` elements as a special case for the 'use' attribute.

**Comment by pgfearo** [comment]
Linter and Auto-Complete for 'use` attribute on `xsl:global-context-item` and `xsl:context-item` are now fixed. Awaiting release.

**Comment by pgfearo** [comment]
Released
