### ISSUE TITLE
XML Auto tag-close

### ISSUE THREAD

**Issue by Ajaja** [DeltaXML/vscode-xslt-tokenizer#31]
Does Auto tag-close  work only with `<xsl:...>` tags?
It doesn't want to automatically close html tags like <td> and other custom XML tags.

**Comment by pgfearo** [comment]
Auto tag-close (triggered by typing `</` ) works should work in any file that has got a recognised XML extension or the '.xsl' extension - provided that the content is well formed. 

It will not work with HTML tags, unless it is well-formed XHTML.

If you're not able to get it working for XML tags please provide an XML snippet that will allow me to reproduce the issue.

**Comment by Ajaja** [comment]
It doesn't  work in my case. A simple xsl , for example:
```
<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0" >
     <xsl:output encoding="utf-8" indent="yes" method="html"/>
     <xsl:template match="/">
        <html>
            <head>
                <title>Test</title>
            </head>
            <body>
                <h1>Test</h1>
            </body>
        </html>
    </xsl:template>
</xsl:stylesheet>
```
It looks like:
![image](https://user-images.githubusercontent.com/297472/97847250-010c9100-1cf8-11eb-87ec-5ada9bdb7269.png)

**Comment by Ajaja** [comment]
I installed XML Tools, it fixed the problem.

**Comment by pgfearo** [comment]
I'm glad this immediate issue is fixed for you by installing XML Tools. However, because there is a lot of overlap in functionality, you may now find that other XSLT features from the XSLT/XPath extension (like formatting) don't work as you would like.

I'm not able to reproduce this auto-tag-close issue myself:

Using your provided XSLT and v0.1.8 of the XSLT/XPath extension (and no other installed extensions) the auto-tag-close feature works on my MacOS machine, the `h1` tag is closed as soon as I type the `/` char in `</`

**Comment by Ajaja** [comment]
You are right. XML Tools is not very handy tool for XSLT. I switched to Auto Close Tag. 
I use Window version of VSCode with Windows 10.  I did try to disable all other extensions  but the issue was still here.

**Comment by pgfearo** [comment]
I think I understand why you're experiencing this issue now:

The auto-tag-close feature requires the `formatOnType` feature to be enabled in VSCode settings. This is because auto-tag-close affects indentation but also because it was more efficient to extend the formatting-provider than to add the feature independently.

I would recommend setting the `formatOnType` property to `true` anyway because of the benefits you get with 'as-you-type' formatting of multi-line XPath expressions as well as nested XML elements.

More details on formatting are documented at: [Editor Settings For Formatting](https://github.com/DeltaXML/vscode-xslt-tokenizer#editor-settings-for-formatting)

**Comment by Ajaja** [comment]
Yes,  `formatOnType` did the trick. Thank you!
