### ISSUE TITLE
Auto-Completion stops working inside elements with default namespace

### ISSUE THREAD

**Issue by Cutuchiqueno** [DeltaXML/vscode-xslt-tokenizer#33]
The intellisense/auto-completion functionality stops working when the cursor is below an element in the xml-tree with default namespace, i.e. without a namespace prefix.

Cosidering the following example:

```xsl
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tei="http://www.tei-c.org/ns/1.0"
  xmlns:melusina="http://www.melusinapress.lu/ns/1.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://datacite.org/schema/kernel-4"
  xsi:schemaLocation="http://datacite.org/schema/kernel-4 http://schema.datacite.org/meta/kernel-4/metadata.xsd"
  version="2.0" exclude-result-prefixes="#all">

...

  [1]
  <xsl:template name="pubInfo">
    [2]
    <publisher>
      [3]
      <xsl:value-of select="/tei:TEI/tei:teiHeader/tei:fileDesc/tei:publicationStmt/tei:publisher/tei:orgName[@role = 'project']"/>
    </publisher>
    <publicationYear>
      <xsl:value-of select="substring(tei:TEI/tei:teiHeader/tei:fileDesc/tei:publicationStmt/tei:date/@when, 1, 4)"/>
    </publicationYear>
  </xsl:template>
```
intellisense/auto-completion works well at position 1 and 2. At position 3, however, I get now intellisense/auto-completion, for none of the namespaces.

Environment:

- Manjaro Linux
- VSCode 1.51

**Comment by pgfearo** [comment]
I see that you're using a 'xsi:schemaLocation' hint in the root element. This extension only provides XSLT auto-completion, I'm afraid there is no auto-completion for XML schemas or DTDs.

The behaviour when typing '<'  in position 3 is as expected on my macOS system - VSCode 1.51.1:

![Screenshot 2020-11-19 at 14 26 44](https://user-images.githubusercontent.com/2734234/99679420-d5b5d000-2a73-11eb-923e-a387774e5e82.png)

**Comment by Cutuchiqueno** [comment]
Thank you for pushing me into the right direction. I only was thinking about completion, but not that I use both RedHats XML Extension and yours.

Thus, the problem is indeed with the one from RedHat. It would be great though to be able to use both extensions at the same time and get completions from one and the other. But I do not know if this is even possible.

**Comment by pgfearo** [comment]
@Cutuchiqueno Regarding compatibility with RedHat's XML extension:

This extension uses the 'xslt' language id for files with a '.xsl' file extension. This is to prevent conflict with VSCode's built-in extension for XSLT that uses the 'xsl' language id but doesn't really do anything except prevents bracket-matching in XPath expressions).

For these extensions to co-exist, the RedHat extension would probably need to support the 'xsl' language id also and drop support for the 'xslt' language id. So this may be something you want to ask the RedHat team about.

I opened a [GitHub issue](https://github.com/microsoft/vscode/issues/99427) regarding this language id conflict with the VSCode team, unfortunately it's been closed because I failed to make a good enough case. I was invited to put in my own PR for this but unfortunately I don't have the expertise/resources for this.

**Comment by Cutuchiqueno** [comment]
@pgfearo Thanks for outlining the source of the problem for me. I will probably open an issue at Red Hat's repository and see if this opens-up a solution. It seems tragic that there is a wonderful XML extension and a wonderful XSLT extension but that it is not possible to have them both working together.
